Repository Eclipse-Station/NEV-Northern-Light, pull requests merged in 2020-05, with the labels that each got.

#14 Removed more Eris stuff I missed.
  code/controllers/subsystems/economy.dm
  code/datums/autolathe/cells.dm
  code/datums/autolathe/parts.dm
  code/game/jobs/department.dm
  code/game/jobs/job/church.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/power_cells.dm
  code/game/objects/items/weapons/tools/misc.dm
  code/game/objects/items/weapons/tools/mods/mod_types.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/cyberplants.dm
  code/modules/economy/Accounts.dm
  code/modules/economy/economy_misc.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Eclipse edit, Lore Compliance, Spelling and Grammer

#15 Serbomat: Phase 1 Changes
  cev_eris.dme
  code/game/machinery/vending.dm
  code/game/machinery/vending_eclipse.dm
Labels: Balance/Rebalance, Lore Compliance, Priority: High, Sprites

#17 Fixes and updates:
  cev_eris.dme
  code/__DEFINES/items_clothing.dm
  code/__HELPERS/global_lists.dm
  code/_helpers/global_lists.dm
  code/_onclick/hud/screen_objects/base_screen_objects.dm
  code/controllers/configuration_eclipse.dm
  code/game/gamemodes/storyteller.dm
  code/game/gamemodes/storytellers/chronicler.dm
  code/game/gamemodes/storytellers/healer.dm
  code/game/gamemodes/storytellers/jester.dm
  code/game/jobs/manifest_controller.dm
  code/game/jobs/whitelist.dm
  code/game/verbs/ooc.dm
  code/modules/materials/material_sheets.dm
  code/modules/mob/new_player/new_player.dm
  icons/mob/zone_sel.dmi
Labels: Balance/Rebalance, Priority: High, Sprites, bugfix, enhancement

#16 Removed NeoTheology mentions + Misc Eris Fixes.
  code/__DEFINES/jobs.dm
  code/__HELPERS/manifest.dm
  code/datums/outfits/jobs/church.dm
  code/game/antagonist/station/inquisitor.dm
  code/game/jobs/access_datum.dm
  code/game/jobs/department.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/church.dm
  code/game/jobs/job/guild.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/structures/signs.dm
  code/modules/cargo/packs.dm
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/client/preference_setup/loadout/lists/misc.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/core_implant/cruciform/bible.dm
  code/modules/core_implant/cruciform/machinery/altar.dm
  code/modules/core_implant/cruciform/machinery/cloning.dm
  code/modules/core_implant/cruciform/machinery/obelisk.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
  code/modules/core_implant/cruciform/upgrades.dm
  code/modules/flufftext/Dreaming.dm
  code/modules/paperwork/stamps.dm
  code/modules/projectiles/guns/energy/egun.dm
  code/modules/projectiles/guns/projectile/automatic/straylight.dm
  code/modules/projectiles/guns/projectile/automatic/wintermute.dm
  code/modules/tips_and_tricks/jobs.dm
Labels: Eclipse edit, Lore Compliance

#18 Changing some erronious mentions of 'Ironhammer' to 'Aegis'.
  code/game/antagonist/station/marshal.dm
  code/game/jobs/job/security.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/stashes/stash_types/junk.dm
Labels: Eclipse edit, Lore Compliance

#22 Unathi sprite fixes, part 1
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Ready for review, Sprites, Work in Progress, bugfix, help wanted

#33 Upstream bot
  tools/merge-upstream-pull-request.sh
Labels: GitHub/CI, Tools

#42 fixes botanist access
  code/game/jobs/job/civilian.dm
Labels: Eclipse edit, bugfix

#41 [MIRROR] More compact crafting menu by grouping variations of the same item
  code/__DEFINES/craft.dm
  code/datums/craft/menu.dm
  code/datums/craft/recipe.dm
  code/datums/craft/recipes/airlocks.dm
  code/datums/craft/recipes/floor.dm
  code/datums/craft/recipes/furniture.dm
  code/datums/craft/recipes/misc.dm
Labels: Upstream PR Merged

#44 [MIRROR] Fixes bad mech qdel
  code/modules/mechs/mech.dm
Labels: Upstream PR Merged

#49 Fixes majority of glove and shoe interaction issues (including insula…
  code/ZAS/Phoron.dm
  code/__DEFINES/items_clothing.dm
  code/__HELPERS/global_lists.dm
  code/game/objects/items.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/organs/external/_external.dm
  code/modules/organs/external/subtypes/robotic.dm
  code/modules/power/power.dm
  code/modules/research/designs/prosthesis_implants.dm
  code/modules/surgery/internal.dm
  icons/obj/mining.dmi
Labels: Priority: High, bugfix

#57 [MIRROR] Fixes the Blitzshell being on accessible camera networks
  code/modules/mob/living/silicon/robot/drone/blitzshell.dm
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Upstream PR Merged

#58 [MIRROR] Add holowarrant object + Adjust holowarrant console programme
  cev_eris.dme
  code/game/objects/items/devices/holowarrant.dm
  code/modules/modular_computers/file_system/programs/security/digitalwarrant.dm
  icons/obj/device.dmi
  nano/templates/digitalwarrant.tmpl
Labels: Upstream PR Merged

#59 [MIRROR] Fix electric chair not working
  code/game/objects/structures/electricchair.dm
Labels: Upstream PR Merged

#64 [MIRROR] Fixes the sanity runtime
  code/modules/reagents/reagents/toxins.dm
  code/modules/sanity/sanity_mob.dm
Labels: Upstream PR Merged

#61 [MIRROR] Changelog Generation - Documentation Port
  .github/workflows/compile_changelogs.yml
  .github/workflows/make_changelogs.yml
  tools/changelog/generate_cl.py
Labels: Upstream PR Merged

#70 [MIRROR] Add t-ray hider for storage and add example stash
  code/game/objects/items/devices/t_scanner.dm
  code/game/objects/items/weapons/storage/storage.dm
  code/modules/stashes/stash_items.dm
Labels: Upstream PR Merged

#65 [MIRROR] Antag objectives no more
  cev_eris.dme
  code/__DEFINES/gamemode.dm
  code/game/antagonist/antagonist_print.dm
  code/game/antagonist/outer/blitzshell/blitzshell.dm
  code/game/antagonist/station/changeling.dm
  code/game/antagonist/station/traitor.dm
  code/game/gamemodes/roleset/double_agents.dm
Labels: Upstream PR Merged

#69 [MIRROR] Blitzshell drop item fixes
  code/modules/mob/living/silicon/robot/drone/blitzshell.dm
Labels: Upstream PR Merged

#72 [MIRROR] Increases amout of supported changelog prefixes
  tools/changelog/ss13_genchangelog.py
Labels: Upstream PR Merged

#74 [MIRROR] Fixes typo in the CL generator
  tools/changelog/ss13_genchangelog.py
Labels: Upstream PR Merged

#82 mi fix janitour acciess
  code/game/jobs/job/civilian.dm
Labels: Eclipse edit, bugfix

#75 [MIRROR] Fix of a cloner
  code/modules/core_implant/cruciform/machinery/cloning.dm
Labels: Upstream PR Merged

#80 [MIRROR] Wall-mounted closets
  cev_eris.dme
  code/game/machinery/walllockers.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/game/objects/structures/crates_lockers/closets/wall_mounted.dm
  code/game/objects/structures/crates_lockers/closets/walllocker.dm
  icons/obj/vending.dmi
  icons/obj/wall_mounted.dmi
  icons/obj/walllocker.dmi
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/centcomm.dmm
Labels: Upstream PR Merged

#84 [MIRROR] Fix cyborgs not being able to pick up stuff (ores, sheets, ...)
  code/_onclick/cyborg.dm
Labels: Upstream PR Merged

#85 [MIRROR] New way to define in which direction a craft should be spawned
  code/__DEFINES/craft.dm
  code/datums/craft/recipe.dm
  code/datums/craft/recipes/machinery.dm
Labels: Upstream PR Merged

#86 [MIRROR] Excel randomstash nerf
  code/modules/stashes/stash_types/excelsior.dm
Labels: Upstream PR Merged

#87 [MIRROR] Fixes Ztravel letting you become alpha-invisible from spamming it
  code/modules/multiz/ztravel/climb.dm
  code/modules/multiz/ztravel/jetpack.dm
  code/modules/multiz/ztravel/zmethod.dm
Labels: Upstream PR Merged

#91 [MIRROR] New bottle sprites
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  icons/obj/chemical.dmi
  icons/obj/reagentfillings.dmi
Labels: Upstream PR Merged

#94 [MIRROR] Watler's new lighter sprites
  code/game/objects/items/weapons/cigs_lighters.dm
  icons/obj/items.dmi
Labels: Upstream PR Merged

#95 [MIRROR] Preacher hat
  code/datums/outfits/jobs/church.dm
  code/datums/uplink/neotheology.dm
  code/modules/clothing/head/jobs.dm
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
Labels: Upstream PR Merged

#60 [MIRROR] German prefix
  code/modules/mob/language/german.dm
Labels: Upstream PR Merged

#89 [MIRROR] Changed how the radio prefix is read irregardless of capitlization used
  code/modules/mob/say.dm
Labels: Upstream PR Merged

#90 [MIRROR] More aesthetic cryostorage
  maps/CEVEris/_CEV_Eris.dmm
Labels: Upstream PR Merged

#97 [MIRROR] [READY]Initial perk system redesign
  cev_eris.dme
  code/__DEFINES/items.dm
  code/_onclick/item_attack.dm
  code/_onclick/other_mobs.dm
  code/datums/mind.dm
  code/datums/mob_stats.dm
  code/datums/perks/combat.dm
  code/datums/perks/job.dm
  code/datums/perks/perk.dm
  code/datums/setup_option/setup_option.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/guild.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/objects/items/oddities.dm
  code/game/objects/random/packs.dm
  code/modules/client/asset_cache.dm
  code/modules/core_implant/cruciform/cruciform.dm
  code/modules/core_implant/cruciform/machinery/cloning.dm
  code/modules/core_implant/cruciform/machinery/obelisk.dm
  code/modules/economy/cash.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/drone/_drone.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/gun.dm
  code/modules/reagents/metabolism.dm
  code/modules/sanity/inspiration_component.dm
  code/modules/sanity/sanity_mob.dm
  code/modules/stashes/stash_datum.dm
  code/modules/stashes/stash_spawner.dm
  code/modules/stashes/stash_types/weapons.dm
  icons/effects/perks.dmi
Labels: Upstream PR Merged

#98 [MIRROR] Smaller grenade shell sprites
  icons/obj/ammo.dmi
Labels: Upstream PR Merged

#99 [MIRROR] Half helmets and wig fix, CM access to maintenance.
  code/game/jobs/job/civilian.dm
  code/modules/clothing/head/armor.dm
  code/modules/clothing/head/misc.dm
Labels: Upstream PR Merged

#103 [MIRROR] WatlerJe Disposal Chute
  icons/obj/pipes/disposal.dmi
Labels: Upstream PR Merged

#104 [MIRROR] Paperwork config lock
  code/controllers/configuration.dm
  code/modules/paperwork/paper.dm
Labels: Upstream PR Merged

#106 [MIRROR] Fix crafting system not checking the required material
  code/datums/craft/step.dm
  code/modules/materials/material_sheets.dm
Labels: Upstream PR Merged

#108 [MIRROR] Add holowarrants to security vendors
  code/game/machinery/vending.dm
Labels: Upstream PR Merged

#105 [MIRROR] New matchbox
  icons/obj/cigarettes.dmi
Labels: Upstream PR Merged

#115 [MIRROR] Fix bedsheet duplication and storage issue
  code/game/objects/structures/bedsheet_bin.dm
Labels: Upstream PR Merged

#116 [MIRROR] No-client Ghost fix and Mech emergency fixes
  cev_eris.dme
  code/modules/mechs/_mech.dm
  code/modules/mechs/components/body.dm
  code/modules/mechs/mech_misc.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/observer/ghost/ghost.dm
Labels: Upstream PR Merged

#126 [MIRROR] New glove icons
  code/modules/clothing/gloves/miscellaneous.dm
  icons/inventory/hands/icon.dmi
  icons/inventory/hands/mob.dmi
Labels: Sprites, Upstream PR Merged, enhancement

#135 [MIRROR] fix pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GitHub/CI, Ready for review, Upstream PR Merged

#128 [MIRROR] Marshal cannot target another marshal
  code/datums/objective/assassinate_marshal.dm
Labels: Upstream PR Merged, bugfix

#133 Fixes #37 Unathi horns and frills displayed as ERROR on preview as well as Tajaran and Skrell specific hair styles also showing the same error. Fixes a Unathi, Tajaran and Vulpkanin tail colouration issue. Fixes #26 wings and tails from the extras menu not showing when facing north.
  cev_eris.dme
  code/modules/mechs/_mech_setup.dm
  code/modules/mechs/mech.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/station/station_vr.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/external/organ_icon.dm
  code/modules/sprite_accessories/extra.dm
  code/modules/sprite_accessories/sprite_accessories_vr.dm
  icons/mob/human_face.dmi
  icons/mob/unathi_extras.dmi
Labels: Eclipse edit, Priority: High, Ready for review, Sprites, bugfix
