Repository Eclipse-Station/NEV-Northern-Light, pull requests merged in 2020-07, with the labels that each got.

#265 fixes the zippo not having an active icon
  icons/obj/items.dmi
Labels: Sprites, bugfix

#266 Hand-and-foot-code fix-up bundle!
  code/game/objects/items/stacks/medical.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  code/modules/mob/living/carbon/human/stripping.dm
  code/modules/mob/mob.dm
  icons/mob/human_races/monkeys/r_monkey.dmi
Labels: Hand and foot code, Priority: High, Quality of Life, Sprites, bugfix

#264 adds another deepmaint room, fixes phoron deepmaint map
  maps/submaps/deepmaint_rooms/normal/normal_rooms.dm
  maps/submaps/deepmaint_rooms/normal/oopsitsbeartraps.dmm
  maps/submaps/deepmaint_rooms/normal/oopsitsphoron.dmm
Labels: CI failure, Feature, Map Changes, bugfix

#263 The Gun Vending Machine Update
  cev_eris.dme
  code/game/machinery/vending_eclipse.dm
  maps/CEVEris/_CEV_Eris.dmm
  zzz_modular_eclipse/gunvendor/gunkits.dm
  zzz_modular_eclipse/gunvendor/vendor.dmi
Labels: Feature, Map Changes, Sprites

#270 Fixed paper bin sprites and messages.
  code/modules/paperwork/paperbin.dm
Labels: bugfix

#223 [MIRROR] Admin tools sol
  cev_eris.dme
  code/datums/topic/admin.dm
  code/modules/admin/DB ban/delayed_ban.dm
  code/modules/admin/DB ban/functions.dm
  code/modules/admin/NewBan.dm
Labels: Administrative, Upstream PR Merged

#251 [MIRROR] Advanced subsurface ore detector
  code/modules/mining/drilling/scanner.dm
  code/modules/research/designs/mining.dm
  code/modules/research/nodes/engineering.dm
Labels: Balance/Rebalance, Upstream PR Merged

#252 [MIRROR] Repair platform
  cev_eris.dme
  code/game/machinery/repairstation.dm
  code/game/objects/items/weapons/circuitboards/machinery/recharge_station.dm
  code/game/objects/random/circuitboards.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/nodes/robotics.dm
  maps/submaps/deepmaint_rooms/normal/mechbay.dmm
Labels: Feature, Map Changes, Upstream PR Merged

#253 [MIRROR] Some groundwork for desire conversion
  code/__DEFINES/sanity.dm
  code/modules/sanity/sanity_mob.dm
Labels: Upstream PR Merged, bugfix

#254 [MIRROR] Nerfs excel armor to IH voidsuit levels
  code/modules/clothing/spacesuits/void/excelsior.dm
Labels: Balance/Rebalance, Upstream PR Merged

#268 [MIRROR] Fixes money being used as an inspiration by players without the required perk
  code/modules/sanity/sanity_mob.dm
Labels: Upstream PR Merged, bugfix

#250 [MIRROR] Jumpsuit for Paramedic
  code/datums/outfits/jobs/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/clothing/under/jobs/medsci.dm
Labels: Feature, Upstream PR Merged

#259 [MIRROR] Makes changelog actions suck a bit less
  .github/workflows/compile_changelogs.yml
  tools/changelog/generate_cl.py
Labels: GitHub/CI, Upstream PR Merged

#256 [MIRROR] , , , , and smoking
  code/__DEFINES/sanity.dm
Labels: Upstream PR Merged, bugfix

#274 [MIRROR] The Sol carbine no longer has insane recoil
  code/modules/projectiles/guns/projectile/automatic/sol.dm
Labels: Balance/Rebalance, Upstream PR Merged

#249 [MIRROR] Oddity perks
  cev_eris.dme
  code/__DEFINES/perk.dm
  code/__DEFINES/perks.dm
  code/__HELPERS/game.dm
  code/__HELPERS/global_lists.dm
  code/_onclick/click.dm
  code/_onclick/other_mobs.dm
  code/datums/perks/fate.dm
  code/datums/perks/oddity.dm
  code/datums/perks/perk.dm
  code/game/area/areas.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/structures.dm
  code/game/sound.dm
  code/game/turfs/simulated/footsteps.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/stripping.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob_helpers.dm
  code/modules/multiz/structures.dm
  code/modules/organs/internal/eyes.dm
  code/modules/projectiles/gun.dm
  code/modules/reagents/reagents/drugs.dm
  code/modules/sanity/sanity_mob.dm
  code/modules/scrap/scrap.dm
  icons/effects/perks.dmi
Labels: Balance/Rebalance, Feature, Sprites, Upstream PR Merged

#275 [MIRROR] paramedic no longer has melee/bullet/energy armor on his jumpsuit
  code/modules/clothing/under/jobs/medsci.dm
Labels: Balance/Rebalance, Upstream PR Merged

#279 [MIRROR] About 20 new hairstyles
  code/modules/sprite_accessories/_accessory_hair.dm
Labels: Balance/Rebalance, Upstream PR Merged

#280 [MIRROR] Martin resprite
  icons/obj/guns/energy.dmi
  icons/obj/guns/energy/pdw.dmi
Labels: Sprites, Upstream PR Merged

#285 shields deep maint from radiation storms
  code/game/gamemodes/events/weather/rad_storm.dm
Labels: bugfix

#287 Bandanas now have head sprites!
  icons/inventory/head/mob.dmi
Labels: Sprites, bugfix

#292 changes backgrounds to be more generic, changes fate descriptions
  code/datums/perks/job.dm
  code/datums/setup_option/backgrounds/fate.dm
  code/datums/setup_option/backgrounds/origin.dm
Labels: Balance/Rebalance, Lore Compliance, Spelling and Grammer

#278 [MIRROR] Fix Noble, Nightcrwawler and Oborin Syndrome perks
  code/datums/perks/fate.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/login.dm
  code/modules/organs/internal/eyes.dm
Labels: Balance/Rebalance, Upstream PR Merged, bugfix

#326 Terminates text preventing code compile
  code/datums/setup_option/backgrounds/origin.dm
Labels: GitHub/CI, Priority: Critical, Priority: High, bugfix

#306 [MIRROR] fix(autolathe.eject): zero stack amount
  code/game/machinery/autolathe/autolathe.dm
Labels: Upstream PR Merged, bugfix

#307 [MIRROR] Adds more guild crates
  code/modules/cargo/packs.dm
Labels: Balance/Rebalance, Feature, Upstream PR Merged

#309 [MIRROR] fix random job preference.
  code/controllers/subsystems/jobs.dm
Labels: Priority: High, Upstream PR Merged, bugfix

#311 [MIRROR] Engineering icons
  code/datums/outfits/jobs/engineering.dm
  code/datums/outfits/jobs/medical.dm
  code/game/objects/random/cloth.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/client/preference_setup/loadout/lists/headwear.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/suits/jobs.dm
  icons/inventory/feet/mob.dmi
  icons/mob/light_overlays.dmi
  icons/obj/light_overlays.dmi
Labels: Sprites, Upstream PR Merged

#313 [MIRROR] fix(frozen_star | designs & disk_name)
  code/game/objects/items/weapons/autolathe_disks.dm
Labels: Upstream PR Merged, bugfix

#318 [MIRROR] Steelpot no longer blocks facial hair.
  code/modules/clothing/head/armor.dm
Labels: Sprites, Upstream PR Merged

#319 [MIRROR] utf-8 two-byte russian chars hotfix
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/modules/mob/living/say.dm
  code/modules/mob/say.dm
Labels: Quality of Life, Upstream PR Merged

#320 [MIRROR] update(sleeper): add eject_occupant_verb
  code/game/machinery/Sleeper.dm
Labels: Quality of Life, Upstream PR Merged

#321 [MIRROR] kitchen knife respirte
  icons/obj/kitchen.dmi
Labels: Sprites, Upstream PR Merged

#322 [MIRROR] Sanity rework vol1.
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagents/drugs.dm
  code/modules/reagents/recipes.dm
  code/modules/sanity/breakdown.dm
  code/modules/sanity/breakdowns.dm
  code/modules/sanity/sanity_mob.dm
  code/modules/scrap/scrap.dm
Labels: Balance/Rebalance, Upstream PR Merged, bugfix

#312 [MIRROR] fix(gulp_whole): validate ghost before gulp
  code/modules/reagents/reagent_containers/food/drinks.dm
Labels: Upstream PR Merged, bugfix

#305 Ports Virgo's 'spawn character' verb
  cev_eris.dme
  code/modules/admin/verbs/randomverbs_eclipse.dm
Labels: Administrative, Quality of Life

#315 Alarm and radio update
  cev_eris.dme
  code/datums/autolathe/basic_stuff.dm
  code/game/machinery/alarm.dm
  code/game/machinery/vending_eclipse.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/weapons/storage/toolbox.dm
  code/game/objects/random/purerandom.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  maps/CEVEris/_CEV_Eris.dmm
  sound/effects/radio_squelch/squelch1.ogg
  sound/effects/radio_squelch/squelch2.ogg
  sound/effects/radio_squelch/squelch3.ogg
  sound/effects/radio_squelch/squelch4.ogg
  sound/misc/airalarm.ogg
  sound/misc/firealarm.ogg
  zzz_modular_eclipse/radio_sprites/radios.dm
  zzz_modular_eclipse/radio_sprites/xpr.dmi
  zzz_modular_eclipse/radio_squelch/radios.dm
Labels: Feature, Map Changes, Sprites

#324 [MIRROR] Custodian QOL changes proper
  code/datums/outfits/jobs/church.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/modules/clothing/shoes/jobs.dm
  code/modules/clothing/spacesuits/void/neotheology.dm
  code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm
Labels: Feature, Quality of Life, Upstream PR Merged

#329 [MIRROR] Fix creating bounty with invalid PIN
  code/modules/modular_computers/file_system/reports/bounty_entry.dm
Labels: Upstream PR Merged, bugfix

#330 [MIRROR] Fixed borg crew monitor verb in Commands tab
  code/modules/mob/living/silicon/subsystems.dm
Labels: Upstream PR Merged

#331 [MIRROR] Stash image dudos
  code/game/objects/landmarks/storyevent.dm
  code/modules/stashes/stash_datum.dm
Labels: Upstream PR Merged

#332 [MIRROR] update(beartrap.attack_mob): cant stun mech
  code/__DEFINES/is_helpers.dm
  code/game/objects/items/weapons/traps.dm
Labels: Upstream PR Merged

#328 [MIRROR] Added utf-8 encoding to paper and flavors.
  code/modules/mob/mob.dm
  code/modules/paperwork/paper.dm
Labels: Upstream PR Merged

#353 fixes (most of) the hardhat icons so that they properly appear in game
  code/modules/clothing/head/hardhat.dm
  icons/inventory/head/icon.dmi
Labels: Priority: High, Sprites, bugfix

#335 [MIRROR] fixes leisure outift code
  code/modules/clothing/under/miscellaneous.dm
Labels: Sprites, Upstream PR Merged

#341 [MIRROR] clrifle rubbers (sol/caselesspistol) does more agony damage
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Balance/Rebalance, Upstream PR Merged

#343 [MIRROR] makes moebius prototype laser cannon a bit more viable
  code/modules/projectiles/guns/energy/laser.dm
Labels: Balance/Rebalance, Upstream PR Merged

#345 [MIRROR] Alcoholic perk fix
  code/datums/perks/fate.dm
Labels: Balance/Rebalance, Upstream PR Merged, bugfix

#366 [MIRROR] Fixes cisterns.
  code/game/objects/structures/watercloset.dm
Labels: Balance/Rebalance, Feature, Upstream PR Merged

#382 Current Character and occupation display on Main Menu
  code/__DEFINES/jobs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/new_player/new_player.dm
Labels: Feature, Quality of Life

#383 adds tyrant storyteller
  cev_eris.dme
  zzz_modular_eclipse/storytellers/tyrant.dm
Labels: Feature

#385 [MIRROR] Restores stash behavior.
  code/game/objects/landmarks/storyevent.dm
  code/modules/stashes/stash_datum.dm
  code/modules/stashes/stash_types/booze.dm
  code/modules/stashes/stash_types/excelsior.dm
  code/modules/stashes/stash_types/junk.dm
  code/modules/stashes/stash_types/valueables.dm
  code/modules/stashes/stash_types/weapons.dm
Labels: Balance/Rebalance, Upstream PR Merged

#386 [MIRROR] Command stash directions change
  code/modules/stashes/stash_types/captain.dm
Labels: Balance/Rebalance, Upstream PR Merged

#388 [MIRROR] More simple weapon tools
  code/datums/craft/recipes/weapon.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/game/objects/items/weapons/tools/simple_weapons.dm
  code/modules/stashes/stash_types/captain.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Feature, Map Changes, Upstream PR Merged

#333 [MIRROR] Gun rebalance
  cev_eris.dme
  code/datums/autolathe/guns.dm
  code/game/machinery/vending.dm
  code/game/machinery/vending_eclipse.dm
  code/game/objects/items/devices/flash.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/random/gun_upgrade.dm
  code/game/objects/random/guns.dm
  code/game/objects/random/packs.dm
  code/modules/projectiles/guns/energy/shrapnel.dm
  code/modules/projectiles/guns/projectile/automatic/dallas.dm
  code/modules/projectiles/guns/projectile/automatic/sol.dm
  code/modules/projectiles/guns/projectile/automatic/sts35.dm
  code/modules/projectiles/guns/projectile/boltgun.dm
  code/modules/projectiles/guns/projectile/pistol/giskard.dm
  code/modules/projectiles/guns/projectile/pistol/lamia.dm
  code/modules/projectiles/guns/projectile/pistol/mandella.dm
  code/modules/projectiles/guns/projectile/pistol/mk58.dm
  code/modules/projectiles/guns/projectile/pistol/olivaw.dm
  code/modules/projectiles/guns/projectile/pistol/paco.dm
  code/modules/projectiles/guns/projectile/revolver/consul.dm
  code/modules/projectiles/guns/projectile/revolver/deckard.dm
  code/modules/projectiles/guns/projectile/revolver/havelock.dm
  code/modules/projectiles/guns/projectile/shotgun/bojevic.dm
  code/modules/projectiles/guns/projectile/shotgun/bull.dm
  code/modules/projectiles/guns/projectile/shotgun/doublebarrel.dm
  code/modules/projectiles/guns/projectile/shotgun/gladstone.dm
  code/modules/projectiles/guns/projectile/shotgun/pump.dm
  code/modules/projectiles/guns/projectile/shotgun/regulator.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/reagents/reagent_containers/spray.dm
Labels: Balance/Rebalance, Upstream PR Merged

#389 [MIRROR] Adds Tricord to sleepers
  code/game/machinery/Sleeper.dm
  code/modules/reagents/reagents/medicine.dm
Labels: Feature, Upstream PR Merged

#402 Whitelists jobs, patch for Aegis name prefixes
  code/controllers/configuration_eclipse.dm
  code/game/gamemodes/storyteller.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/silicon.dm
  code/modules/mob/living/carbon/human/human.dm
  config/example/config_eclipse.txt
Labels: Administrative, Priority: High, bugfix

#399 adjusts the tyrant to spawn events more frequently, also fixes a typo…
  zzz_modular_eclipse/storytellers/tyrant.dm
Labels: Balance/Rebalance

#404 Nerfs the everliving hell out of Fungo di Artiglieria spawning
  code/controllers/subsystems/migration.dm
  code/modules/hydroponics/spreading/spreading_growth.dm
Labels: Balance/Rebalance

#390 [MIRROR] Fixes "rigged cell explosion" admin log spam
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/power/cell.dm
Labels: Upstream PR Merged, bugfix

#391 [MIRROR] Added ability to fix mecha with welder and wiring.
  code/modules/mechs/components/_components.dm
  code/modules/mechs/mech_interaction.dm
Labels: Balance/Rebalance, Feature, Upstream PR Merged

#393 [MIRROR] Fixes cyborg guns spawning with infinite charge
  code/modules/mob/living/silicon/robot/robot_modules.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/egun.dm
  code/modules/projectiles/guns/energy/lasertag.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/shrapnel.dm
  code/modules/projectiles/guns/energy/stun.dm
Labels: Balance/Rebalance, Upstream PR Merged, bugfix

#394 [MIRROR] Redoes a shitton of GPS stuff
  code/__HELPERS/unsorted.dm
  code/datums/gps_data.dm
  code/game/atoms.dm
  code/game/machinery/computer/prisoner.dm
  code/game/objects/items/devices/radio/beacon.dm
  code/game/objects/items/weapons/implant/implantpad.dm
  code/game/objects/items/weapons/implant/implants/tracking.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/teleportation.dm
  code/game/objects/random/purerandom.dm
  code/modules/modular_computers/hardware/gps_sensor.dm
  code/modules/multiz/map_data.dm
  code/modules/research/xenoarchaeology/tools/tools.dm
  maps/dungeons/deepmaint/deepmaint.dm
Labels: Balance/Rebalance, Upstream PR Merged

#416 Fixes an issue where players could join despite being not whitelisted
  code/modules/mob/new_player/new_player.dm
Labels: Exploit, Priority: High, bugfix

#417 NT Department Alarm Dispatcher (DAD), Part 1
  cev_eris.dme
  code/__DEFINES/subsystems.dm
  code/__HELPERS/logging.dm
  code/controllers/configuration_eclipse.dm
  code/controllers/subsystems/dispatcher.dm
  code/controllers/subsystems/dispatcher_debug.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/requests_console.dm
  code/modules/admin/verbs/randomverbs_eclipse.dm
  code/modules/research/message_server.dm
  config/example/config_eclipse.txt
Labels: Eclipse Code Port, Eclipse edit, Feature, Non-base branch, Quality of Life

#418 NTDAD map changes
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Feature, Map Changes, Non-base branch, bugfix
