Repository Eclipse-Station/NEV-Northern-Light, pull requests merged in 2020-06, with the labels that each got.

#130 [MIRROR] Fixes Tank icon states appearing over mobs.
  code/game/objects/items/weapons/tanks/jetpack.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Sprites, Upstream PR Merged, bugfix

#134 [MIRROR] fix alien machine sprite
  icons/obj/xenoarchaeology.dmi
Labels: Sprites, Upstream PR Merged, bugfix

#136 [MIRROR] Fix runtime in summon_mobs
  code/controllers/subsystems/migration.dm
Labels: Upstream PR Merged, bugfix

#137 [MIRROR] Give a shovel to maintenance drones
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/mob/living/silicon/robot/robot_modules.dm
  icons/obj/robot_items.dmi
Labels: Balance/Rebalance, Upstream PR Merged, enhancement

#140 [MIRROR] Slime grenades
  code/game/objects/items/weapons/grenades/anti_photon_grenade.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/game/objects/items/weapons/grenades/smokebomb.dm
  code/game/objects/items/weapons/grenades/sonic.dm
Labels: Upstream PR Merged, enhancement

#141 [MIRROR] Fixes the blitzshell showing up on manifest
  code/modules/mob/living/silicon/robot/drone/blitzshell.dm
Labels: Upstream PR Merged, bugfix

#138 [MIRROR] Fixes drone control not detecting drones on a different z level
  code/modules/mob/living/silicon/robot/drone/drone_console.dm
Labels: Upstream PR Merged, bugfix

#142 [MIRROR] less .charge, more .give
  code/game/machinery/floodlight.dm
  code/game/machinery/rechargestation.dm
  code/game/objects/items/devices/lighting/toggleable/flashlight.dm
  code/game/objects/items/devices/megaphone.dm
  code/game/objects/items/devices/scanners/scanners.dm
  code/game/objects/items/devices/suit_cooling.dm
  code/game/objects/items/devices/t_scanner.dm
  code/game/objects/items/weapons/RPD.dm
  code/game/objects/items/weapons/RSF.dm
  code/game/objects/items/weapons/space_harpoon.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/items/weapons/teleportation.dm
  code/game/objects/structures/watercloset.dm
  code/modules/clothing/glasses/powered.dm
  code/modules/clothing/gloves/stungloves.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/integrated/integrated_electronics/subtypes/power.dm
  code/modules/mechs/interface/screen_objects.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/ai/login.dm
  code/modules/mob/living/silicon/ai/logout.dm
  code/modules/mob/living/silicon/robot/analyzer.dm
  code/modules/mob/living/silicon/robot/photos.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_damage.dm
  code/modules/mob/living/silicon/robot/robot_parts.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
  code/modules/modular_computers/computers/modular_computer/power.dm
  code/modules/nano/interaction/base.dm
  code/modules/power/apc.dm
  code/modules/power/cell.dm
  code/modules/power/power.dm
  code/modules/power/smes.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/launcher/crossbow.dm
  code/modules/reagents/machinery/electrolyzer.dm
  code/modules/reagents/reagent_containers/borghydro.dm
  code/modules/research/xenoarchaeology/artifact/effects/unknown_effect_cellcharge.dm
  code/modules/vehicles/cargo_train.dm
Labels: Upstream PR Merged, bugfix

#143 [MIRROR] Port various antiraid/antigrief measures
  cev_eris.dme
  code/controllers/configuration.dm
  code/modules/admin/admin_ranks.dm
  code/modules/admin/verbs/antiraid.dm
  code/modules/client/client procs.dm
  code/modules/client/client_defines.dm
  config/example/config.txt
Labels: Tools, Upstream PR Merged, enhancement

#145 [MIRROR] Homewrecker fits on back and belt. Does 26 damage when wielded.
  code/game/objects/items/weapons/tools/hammer.dm
Labels: Balance/Rebalance, Upstream PR Merged

#146 [MIRROR] Update client procs.dm
  code/modules/client/client procs.dm
Labels: Diff oddities, Upstream PR Merged

#150 [MIRROR] Random fixes
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/deployable.dm
  code/game/machinery/recharger.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/tables/tables.dm
Labels: Upstream PR Merged, bugfix

#149 [MIRROR] Fix runtime in priest.dm
  code/modules/core_implant/cruciform/rituals/priest.dm
Labels: Upstream PR Merged, bugfix

#148 [MIRROR] Fix runtime in spiderbot.dm
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
Labels: Upstream PR Merged, bugfix

#153 [MIRROR] Fix runtime in mind.dm
  code/datums/mind.dm
Labels: Upstream PR Merged, bugfix

#152 [MIRROR] Adjusts burrow migrations
  code/controllers/subsystems/migration.dm
Labels: Balance/Rebalance, Upstream PR Merged

#151 [MIRROR] Fix runtime with perks in mob.dm
  code/modules/mob/mob.dm
Labels: Upstream PR Merged, bugfix

#155 [MIRROR] Fixes "altyn" and "maska" helmet armor values being broken
  code/modules/clothing/head/armor.dm
Labels: Upstream PR Merged

#158 [MIRROR] Tweak roach and spider behavior with windows
  code/modules/mob/living/carbon/superior_animal/ai.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
Labels: Upstream PR Merged

#159 [MIRROR] Add tobacco seeds and leaves to hydroponics
  code/game/machinery/vending.dm
  code/modules/hydroponics/seed_datums.dm
  icons/obj/hydroponics_products.dmi
Labels: Upstream PR Merged

#147 [MIRROR] Fixes private servers CTDing themselves
  code/modules/client/client procs.dm
Labels: Diff oddities, Upstream PR Merged, bugfix

#125 [MIRROR] Tank & Belt icons, PermaBrig feature
  code/datums/autolathe/biomatter.dm
  code/game/machinery/biogenerator.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/tanks/onestar_regenerator.dm
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/game/objects/random/cloth.dm
  code/game/objects/random/purerandom.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/paperwork/paper_premade.dm
  icons/inventory/back/mob.dmi
  icons/inventory/belt/icon.dmi
  icons/inventory/belt/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/closet.dmi
  icons/obj/tank.dmi
  maps/CEVEris/_CEV_Eris.dmm
  maps/CEVEris/centcomm.dmm
Labels: Map Changes, Sprites, Upstream PR Merged

#156 [MIRROR] Fixes a runtime in log_client_to_db
  code/modules/client/client procs.dm
Labels: Upstream PR Merged, bugfix

#160 [MIRROR] option "send back to lobby"
  code/datums/topic/admin.dm
  code/datums/topic/topic_handlers.dm
  code/modules/admin/admin.dm
Labels: Feature, Upstream PR Merged

#161 [MIRROR] Fixes the runtime with floor sound
  code/game/turfs/turf.dm
Labels: Upstream PR Merged, bugfix

#165 [MIRROR] Removes two more client qdels
  code/datums/topic/admin.dm
Labels: Upstream PR Merged, bugfix

#166 [MIRROR] Fixed damage type of the combat drone's laser.
  code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
Labels: Upstream PR Merged, bugfix

#164 [MIRROR] Excel rework part 1 - Mandates
  cev_eris.dme
  code/controllers/subsystems/ticker.dm
  code/datums/autolathe/devices.dm
  code/datums/contract.dm
  code/datums/objective/rev.dm
  code/datums/perks/job.dm
  code/game/antagonist/antagonist_factions.dm
  code/game/antagonist/antagonist_print.dm
  code/game/antagonist/station/revolutionary/excel_faction.dm
  code/game/machinery/excelsior/ex_teleporter.dm
  code/game/objects/items/devices/mind_fryer.dm
  code/game/objects/items/devices/propaganda_chip.dm
  code/game/objects/items/devices/spy_sensor.dm
  code/game/objects/items/devices/uplink.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/implant/implants/spying.dm
  code/game/objects/items/weapons/storage/bsdm.dm
  code/modules/mob/living/living.dm
  icons/obj/contraband.dmi
  nano/images/uiBackground-Excelsior.png
  nano/images/uiTitleFluff-Excelsior.png
  nano/js/nano_base_helpers.js
  nano/templates/excelsior_teleporter.tmpl
Labels: Feature, Upstream PR Merged

#168 [MIRROR] Roaches will now eat human corpses
  cev_eris.dme
  code/game/objects/effects/roaches.dm
  code/game/objects/effects/spiders.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/superior_animal/defense.dm
  code/modules/mob/living/carbon/superior_animal/giant_spider/giant_spider.dm
  code/modules/mob/living/carbon/superior_animal/life.dm
  code/modules/mob/living/carbon/superior_animal/roach/life.dm
  code/modules/mob/living/carbon/superior_animal/roach/roach.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/roachling.dm
  code/modules/mob/living/carbon/superior_animal/superior_animal.dm
  icons/effects/effects.dmi
  icons/mob/animal.dmi
Labels: Feature, Upstream PR Merged

#169 [MIRROR] Removes yet another client qdel
  code/datums/topic/admin.dm
Labels: Upstream PR Merged, bugfix

#170 [MIRROR] Fixes excel typos in code
  code/datums/contract.dm
Labels: PR dependencies, Spelling and Grammer, Upstream PR Merged

#157 [MIRROR] Exosuit fixes, tweaks, improvements and other kinds of bullshit
  cev_eris.dme
  code/__DEFINES/is_helpers.dm
  code/game/machinery/autolathe/autolathe.dm
  code/game/machinery/autolathe/mechfab.dm
  code/game/objects/objs.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
  code/modules/bs_snare/machinery.dm
  code/modules/bs_snare/snare.dm
  code/modules/cargo/packs.dm
  code/modules/mechs/_mech_defines.dm
  code/modules/mechs/_mech_setup.dm
  code/modules/mechs/components/_components.dm
  code/modules/mechs/components/armour.dm
  code/modules/mechs/components/arms.dm
  code/modules/mechs/components/body.dm
  code/modules/mechs/components/frame.dm
  code/modules/mechs/components/head.dm
  code/modules/mechs/components/legs.dm
  code/modules/mechs/components/software.dm
  code/modules/mechs/equipment/medical.dm
  code/modules/mechs/interface/screen_objects.dm
  code/modules/mechs/mech.dm
  code/modules/mechs/mech_construction.dm
  code/modules/mechs/mech_damage.dm
  code/modules/mechs/mech_interaction.dm
  code/modules/mechs/mech_life.dm
  code/modules/mechs/mech_movement.dm
  code/modules/mechs/mech_radio.dm
  code/modules/mechs/mech_recharger.dm
  code/modules/mechs/mech_wreckage.dm
  code/modules/mechs/premade/_premade.dm
  code/modules/mechs/premade/combat.dm
  code/modules/mechs/premade/heavy.dm
  code/modules/mechs/premade/light.dm
  code/modules/mechs/premade/powerloader.dm
  code/modules/mining/coins.dm
  code/modules/mob/living/silicon/robot/component.dm
  code/modules/mob/living/silicon/robot/robot_parts.dm
  code/modules/research/designs/mechs2/_exosuits.dm
  code/modules/research/designs/mechs2/exosuits_components.dm
  code/modules/research/designs/mechs2/exosuits_equipment.dm
  code/modules/research/nodes/robotics.dm
  icons/mechs/mech_equipment.dmi
  nano/templates/autolathe.tmpl
Labels: Balance/Rebalance, Upstream PR Merged, bugfix

#171 [MIRROR] Fix blitzshell blood extraction and ancient teleporter restriction.
  code/game/objects/items/weapons/storage/bsdm.dm
  code/modules/dungeons/teleporter.dm
  code/modules/mob/living/silicon/robot/drone/blitzshell.dm
  code/modules/reagents/reagent_containers/syringes.dm
Labels: Balance/Rebalance, Upstream PR Merged, bugfix

#172 [MIRROR] Removes more client qdel bullshit
  code/modules/client/client procs.dm
Labels: Upstream PR Merged, bugfix

#173 [MIRROR] Adds bee crate to guild
  code/modules/cargo/packs.dm
Labels: Feature, Upstream PR Merged

#174 [MIRROR] Fix runtime in who.dm
  code/game/verbs/who.dm
Labels: Upstream PR Merged, bugfix

#193 Mapfix
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, PR dependencies, Priority: High

#175 [MIRROR] Propaganda_chip runtime fix
  code/game/objects/items/devices/propaganda_chip.dm
Labels: Upstream PR Merged, bugfix

#177 [MIRROR] New Food ingredient sprites
  icons/obj/food_ingredients.dmi
Labels: Sprites, Upstream PR Merged

#178 [MIRROR] Shatter fix
  code/modules/mob/mob_helpers.dm
Labels: Upstream PR Merged, bugfix

#179 [MIRROR] Fixed some text from the AI
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Lore Compliance, Upstream PR Merged

#181 [MIRROR] Blitzshell fast fix.
  code/game/objects/items/weapons/storage/bsdm.dm
  code/modules/mob/living/silicon/robot/drone/blitzshell.dm
Labels: Upstream PR Merged, bugfix

#183 [MIRROR] Adds a weedkiller firemode to the NT BCR
  code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm
Labels: Balance/Rebalance, Feature, Upstream PR Merged

#184 [MIRROR] Hidden events: Kaiser Roach
  cev_eris.dme
  code/game/gamemodes/events/hidden_events/kaiser.dm
  code/game/objects/structures/burrows.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/support.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/toxic.dm
  icons/mob/64x64.dmi
Labels: Feature, The stuff of nightmares!, Upstream PR Merged

#180 [MIRROR] Added INFRARED_BARON's sprites in loadout
  code/game/objects/random/cloth.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: Sprites, Upstream PR Merged

#187 [MIRROR] Technomancer attire, yellow glasses
  code/modules/client/preference_setup/loadout/lists/eyegear.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/meson.dm
  code/modules/clothing/glasses/misc.dm
  code/modules/clothing/under/jobs/engineering.dm
  icons/inventory/eyes/icon.dmi
  icons/inventory/eyes/mob.dmi
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
Labels: Feature, Sprites, Upstream PR Merged

#188 [MIRROR] Excel rework part 2 - Items
  cev_eris.dme
  code/datums/autolathe/circuits.dm
  code/datums/autolathe/guns.dm
  code/datums/contract.dm
  code/game/machinery/excelsior/boombox.dm
  code/game/machinery/excelsior/ex_teleporter.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/items/weapons/circuitboards/machinery/excelsior.dm
  code/game/objects/items/weapons/stock_parts.dm
  code/modules/clothing/under/excelsior.dm
  code/modules/projectiles/guns/matter/launcher/reclaimer.dm
  code/modules/reagents/reagents/other.dm
  icons/obj/guns/matter/reclaimer.dmi
  icons/obj/machines/excelsior/boombox.dmi
  icons/obj/projectiles.dmi
  icons/obj/stock_parts.dmi
  nano/templates/excelsior_teleporter.tmpl
Labels: Feature, Sprites, Upstream PR Merged

#189 [MIRROR] Fixes Sleek Jacket and Jaeger Jacket
  code/modules/clothing/suits/miscellaneous.dm
Labels: Upstream PR Merged, bugfix

#182 [MIRROR] Blitzshell drone riping heads off!
  code/modules/mob/living/silicon/robot/drone/blitzshell.dm
Labels: Feature, Upstream PR Merged

#185 [MIRROR] fixes the NT spray altfire
  code/modules/projectiles/guns/matter/launcher/nt_sprayer.dm
Labels: Upstream PR Merged, bugfix

#190 [MIRROR] JPdungeon path generator simple optimization
  code/modules/dungeons/procedural/jp_dungeon_gen.dm
Labels: PR dependencies, Point Of Interest, Upstream PR Merged, bugfix

#191 [MIRROR] Deepmaint fixes and optimizations + multiz pulling fix
  code/modules/dungeons/procedural/deepmaint.dm
  code/modules/dungeons/procedural/jp_dungeon_gen.dm
  code/modules/multiz/movement.dm
  maps/submaps/deepmaint_rooms/normal/sm_core.dmm
Labels: Map Changes, PR dependencies, Point Of Interest, Priority: Critical, Priority: High, Upstream PR Merged, bugfix

#195 [MIRROR] Excel ticker infinte loop fix
  code/controllers/subsystems/ticker.dm
  code/game/objects/items/devices/propaganda_chip.dm
Labels: Upstream PR Merged

#196 Customization Update
  cev_eris.dme
  code/__DEFINES/damage_organs.dm
  code/__DEFINES/maths.dm
  code/__DEFINES/mobs.dm
  code/__HELPERS/atoms.dm
  code/__HELPERS/game.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/icons.dm
  code/datums/datacore.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/events/blob.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/client/preference_setup/customization/01_ears.dm
  code/modules/client/preference_setup/general/02_body.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_organs.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/moth.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/station/station_vr.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_powers.dm
  code/modules/modular_computers/file_system/reports/crew_record.dm
  code/modules/organs/external/_external.dm
  code/modules/size/size.dm
  code/modules/sprite_accessories/extra.dm
  icons/mob/human_races/markings_vr.dmi
  icons/mob/human_races/r_moth.dmi
Labels: Feature, Ready for review, Sprites

#197 Biogenerator / Bioreactor UI additions and improvements
  code/modules/biomatter_manipulation/biogenerator.dm
  code/modules/biomatter_manipulation/bioreactor/bioreactor.dm
  code/modules/biomatter_manipulation/bioreactor/biotank.dm
  code/modules/biomatter_manipulation/bioreactor/console.dm
  code/modules/biomatter_manipulation/bioreactor/platform.dm
  nano/templates/bioreactor.tmpl
  nano/templates/nt_biogen.tmpl
Labels: Eclipse edit, Spelling and Grammer

#200 [MIRROR] ifx bans without cid and fix ip ban
  code/datums/topic/admin.dm
  code/modules/admin/DB ban/functions.dm
Labels: Administrative, Upstream PR Merged, bugfix

#233 Evac signs now glow in the dark
  cev_eris.dme
  zzz_modular_eclipse/evac_sign/evacsign.dm
  zzz_modular_eclipse/evac_sign/evacsign_eclipse.dmi
  zzz_modular_eclipse/readme.md
Labels: Feature, Sprites

#214 [MIRROR] Boss mob fixes
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/kaiser.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hivetechboss.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/onestarboss.dm
  icons/mob/64x64.dmi
Labels: Balance/Rebalance, Sprites, Upstream PR Merged

#208 [MIRROR] Makes trashcarts better at being usefull
  code/game/objects/structures/crates_lockers/crates.dm
Labels: Balance/Rebalance, Upstream PR Merged

#207 [MIRROR] Rnd QoL Sorting and new node!
  code/game/objects/items/devices/lighting/glowstick.dm
  code/modules/research/designs.dm
  code/modules/research/designs/circuits.dm
  code/modules/research/designs/illegal.dm
  code/modules/research/nodes/engineering.dm
  code/modules/research/nodes/illegal.dm
  nano/css/shared.css
  nano/images/science.png
Labels: Feature, Sprites, Upstream PR Merged

#203 [MIRROR] Breakdown admin log fix
  code/modules/sanity/breakdown.dm
Labels: Administrative, Upstream PR Merged

#205 [MIRROR] Hidden events: Bluespace Rift
  cev_eris.dme
  code/game/gamemodes/events/hidden_events/bluespace_rift.dm
  code/game/objects/effects/portals.dm
Labels: Feature, Upstream PR Merged

#211 [MIRROR] Bandaid-fixes robots from spawning in maintenance
  code/game/objects/landmarks/join.dm
  code/modules/client/preferences_spawnpoints.dm
Labels: Upstream PR Merged, bugfix

#213 [MIRROR] Adds duffelbags to preferences
  code/datums/outfits/equipment/backpacks.dm
  code/modules/client/preference_setup/general/04_equipment.dm
Labels: Feature, Upstream PR Merged

#215 [MIRROR] Mapdata tweaks
  code/__DEFINES/holomap.dm
  code/__DEFINES/misc.dm
  code/__HELPERS/turfs.dm
  code/controllers/evacuation/evacuation.dm
  code/controllers/evacuation/evacuation_lifepods.dm
  code/controllers/evacuation/evacuation_pods.dm
  code/controllers/subsystems/jobs.dm
  code/controllers/subsystems/mapping.dm
  code/datums/security_state.dm
  code/defines/procs/announce.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/events/brand_intelligence.dm
  code/game/gamemodes/events/carp_migration.dm
  code/game/gamemodes/events/clang.dm
  code/game/gamemodes/events/dust.dm
  code/game/gamemodes/events/grid_check.dm
  code/game/gamemodes/events/meteors.dm
  code/game/gamemodes/events/radiation_storm.dm
  code/game/gamemodes/events/rogue_drones.dm
  code/game/gamemodes/events/wallrot.dm
  code/game/gamemodes/malfunction/newmalf_ability_trees/tree_networking.dm
  code/game/machinery/alarm.dm
  code/game/machinery/holoposter.dm
  code/game/turfs/turf.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/asset_cache.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/client/preference_setup/occupation/occupation.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/holomap/generate_holomap.dm
  code/modules/holomap/holomap_datum.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/observer/ghost/ghost.dm
  code/modules/modular_computers/file_system/programs/command/card.dm
  code/modules/modular_computers/file_system/programs/command/comm.dm
  code/modules/modular_computers/file_system/programs/engineering/supermatter_monitor.dm
  code/modules/modular_computers/file_system/programs/medical/suit_sensors.dm
  code/modules/modular_computers/file_system/programs/research/email_administration.dm
  code/modules/modular_computers/hardware/network_card.dm
  code/modules/multiz/map_data.dm
  code/modules/nano/nanoui.dm
  code/modules/overmap/_defines.dm
  code/modules/overmap/events/movable.dm
  code/modules/overmap/sectors.dm
  code/modules/overmap/ships/computers/helm.dm
  code/modules/overmap/ships/ship.dm
  code/modules/overmap/spacetravel.dm
  code/modules/power/gravitygenerator.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/security levels/keycard authentication.dm
  code/modules/shuttles/shuttle_emergency.dm
Labels: Spelling and Grammer, Upstream PR Merged

#217 [MIRROR] Balance fix of Energy Dart weakening through armor
  code/modules/projectiles/projectile/energy.dm
Labels: Balance/Rebalance, Upstream PR Merged

#218 [MIRROR] Tactical belts can fit crowbars.
  code/game/objects/items/weapons/storage/belt.dm
Labels: Balance/Rebalance, Upstream PR Merged

#220 [MIRROR] remove unused holomap legend .png
  icons/effects/64x64 2-2.png
  icons/effects/64x64 2-3.png
  icons/effects/64x64 2-4.png
  icons/effects/64x64 2.png
Labels: GitHub/CI, Sprites, Upstream PR Merged

#209 [MIRROR] Fixes certain deepmaint maps
  maps/submaps/deepmaint_rooms/core/ai_core.dmm
  maps/submaps/deepmaint_rooms/core/archive.dmm
  maps/submaps/deepmaint_rooms/core/podbay.dmm
  maps/submaps/deepmaint_rooms/normal/mechbay.dmm
  maps/submaps/deepmaint_rooms/normal/morgue.dmm
Labels: Map Changes, Upstream PR Merged

#224 [MIRROR] delayround button fix
  code/game/gamemodes/storyteller_print.dm
Labels: Administrative, Upstream PR Merged, bugfix

#227 [MIRROR] Better salvageables
  code/game/objects/structures/salvageable.dm
Labels: Balance/Rebalance, Upstream PR Merged

#204 [MIRROR] Fate perks
  cev_eris.dme
  code/__DEFINES/misc.dm
  code/__DEFINES/perk.dm
  code/__HELPERS/game.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/text.dm
  code/__HELPERS/unsorted.dm
  code/controllers/subsystems/initialization/character_setup.dm
  code/datums/objective/objective.dm
  code/datums/perks/fate.dm
  code/datums/perks/job.dm
  code/datums/perks/perk.dm
  code/datums/setup_option/backgrounds/fate.dm
  code/game/antagonist/_antagonist_setup.dm
  code/game/antagonist/antagonist_equip.dm
  code/game/antagonist/antagonist_objectives.dm
  code/game/antagonist/station/traitor.dm
  code/game/dna/genes/gene.dm
  code/game/dna/setup_genetics.dm
  code/game/gamemodes/roleset/roleset.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/mine.dm
  code/game/objects/items/weapons/traps.dm
  code/game/objects/random/traps/traps.dm
  code/game/objects/structures/wire_splicing.dm
  code/game/turfs/simulated/footsteps.dm
  code/modules/assembly/mousetrap.dm
  code/modules/client/client procs.dm
  code/modules/client/preference_setup/background/05_fate.dm
  code/modules/client/preference_setup/general/01_basic.dm
  code/modules/client/preferences.dm
  code/modules/mob/inventory.dm
  code/modules/mob/language/language.dm
  code/modules/mob/language/station.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/taste.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/organs/internal/eyes.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/medicine.dm
  code/modules/sanity/sanity_area.dm
  code/modules/sanity/sanity_atom.dm
  code/modules/sanity/sanity_mob.dm
  icons/effects/perks.dmi
Labels: Feature, Upstream PR Merged

#201 [MIRROR] Fixes the sanity cap
  code/datums/perks/fate.dm
  code/modules/sanity/sanity_mob.dm
Labels: Balance/Rebalance, Feature, Upstream PR Merged, bugfix

#202 [MIRROR] trap logic fix
  code/modules/mob/mob_helpers.dm
Labels: Upstream PR Merged, bugfix

#244 Fixes people not going horizontal anymore
  cev_eris.dme
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/mob.dm
Labels: Priority: High, bugfix

#230 Adjusts flavour text prompt to allow multiline input
  code/modules/client/preference_setup/general/03_flavor.dm
Labels: Eclipse edit, Feature, Quality of Life

#240 [MIRROR] Fixes roaches not being properly deleted upon gibbing
  code/modules/mob/death.dm
Labels: Priority: Critical, Priority: High, Upstream PR Merged, bugfix

#198 Soulcrypt Addition
  cev_eris.dme
  code/__DEFINES/soulcrypt.dm
  code/game/jobs/access.dm
  code/modules/client/preference_setup/general/02_body.dm
  code/modules/core_implant/cruciform/machinery/cloning.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/modular_computers/computers/modular_computer/ui.dm
  code/modules/soulcrypt/_overwrites.dm
  code/modules/soulcrypt/access_update_tool.dm
  code/modules/soulcrypt/base_implant.dm
  code/modules/soulcrypt/debug.dm
  code/modules/soulcrypt/helpers.dm
  code/modules/soulcrypt/holochip.dm
  code/modules/soulcrypt/module.dm
  code/modules/soulcrypt/modules/crew_monitor.dm
  code/modules/soulcrypt/modules/engineering.dm
  code/modules/soulcrypt/modules/prosthetic_diag.dm
  code/modules/soulcrypt/statpanel.dm
  icons/obj/soulcrypt.dmi
Labels: Balance/Rebalance, Feature, Sprites, Work in Progress

#221 [MIRROR] Fixes Excelsior boombox description
  code/game/machinery/excelsior/boombox.dm
Labels: Lore Compliance, Upstream PR Merged

#212 [MIRROR] Fixes riot helmet face shield runtimes
  code/modules/clothing/head/armor.dm
Labels: Upstream PR Merged, bugfix

#222 [MIRROR] Get rid of IHS equipment and rigged cells
  code/game/objects/random/rig.dm
Labels: Balance/Rebalance, Upstream PR Merged

#225 [MIRROR] get rid of IHS voidsuit in random spawn
  code/game/objects/random/voidsuit.dm
Labels: Balance/Rebalance, Upstream PR Merged

#238 [MIRROR] Makes cable coils easier to click
  icons/obj/power.dmi
Labels: Quality of Life, Sprites, Upstream PR Merged

#232 [MIRROR] Fix Fate Perks v1.
  code/datums/perks/fate.dm
  code/datums/setup_option/backgrounds/fate.dm
  code/modules/client/preference_setup/options_popup.dm
  code/modules/sanity/sanity_mob.dm
Labels: PR dependencies, Upstream PR Merged

#239 [MIRROR] Stops fingerprints attempting to qdel a list, which is not possible
  code/game/atoms.dm
Labels: Upstream PR Merged, bugfix

#226 [MIRROR] Noble buff
  code/datums/perks/fate.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
  code/modules/sanity/inspiration_component.dm
  code/modules/sanity/sanity_mob.dm
Labels: PR dependencies, Upstream PR Merged

#243 adds 2 deepmaint rooms aaaaaaaa
  maps/submaps/deepmaint_rooms/normal/normal_rooms.dm
  maps/submaps/deepmaint_rooms/normal/oldchurch.dmm
  maps/submaps/deepmaint_rooms/normal/oopsitsphoron.dmm
Labels: Feature, Map Changes, Point Of Interest

#228 [MIRROR] Adds More Protection to TM Helmet, Patches TE Rig Cape Icon
  code/modules/clothing/head/armor.dm
  code/modules/clothing/spacesuits/rig/modules/modules.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/spacesuits/rig/rig.dm
Labels: Balance/Rebalance, Upstream PR Merged

#241 [MIRROR] Adds the Back-Alley organ disk
  code/datums/autolathe/biomatter.dm
  code/game/objects/items/weapons/autolathe_disks.dm
  code/game/objects/random/lathe_disks.dm
  code/modules/mob/living/carbon/breathe.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/organs/internal/lungs.dm
  icons/obj/surgery.dmi
Labels: Balance/Rebalance, Feature, Sprites, Upstream PR Merged

#245 Partial revert/refactor of character name system
  code/datums/perks/fate.dm
  code/modules/client/preference_setup/general/01_basic.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/new_player/new_player.dm
Labels: Eclipse edit, Lore Compliance

#255 [MIRROR] Fixes bad memory management on stash photos
  code/modules/stashes/stash_datum.dm
Labels: Upstream PR Merged

#258 Adds a "Copy Slot" button to the character menu, as requested in #32
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Feature, Quality of Life

#248 [MIRROR] Fix perk oborin syndrome
  code/datums/perks/fate.dm
  code/modules/mob/living/carbon/taste.dm
Labels: Upstream PR Merged, bugfix
