Repository Eclipse-Station/NEV-Northern-Light, pull requests merged in 2020-08, with the labels that each got.

#414 tweaks trash piles to be slightly less annoying
  code/modules/scrap/scrap.dm
Labels: bugfix

#421 [MIRROR] Placing/Removing gas masks and IV needles using the medical stand should be faster now.
  code/game/objects/structures/medical_stand.dm
Labels: Balance/Rebalance, Quality of Life, Upstream PR Merged

#422 [MIRROR] Bugfix #494
  code/modules/multiz/movement.dm
Labels: Upstream PR Merged, bugfix

#424 [MIRROR] mine changes
  code/game/objects/items/weapons/mine.dm
Labels: Balance/Rebalance, Upstream PR Merged, bugfix

#425 [MIRROR] Fixes intentional wire splicing
  code/game/objects/structures/wire_splicing.dm
  code/modules/power/cable.dm
Labels: Upstream PR Merged, bugfix

#426 [MIRROR] fix_2051
  code/__DEFINES/_planes+layers.dm
  code/modules/mob/living/carbon/brain/brain_item.dm
  code/modules/organs/internal/_internal.dm
Labels: Upstream PR Merged, bugfix

#427 [MIRROR] Fix 2045
  code/game/objects/structures/catwalk.dm
  code/game/objects/structures/lattice.dm
  code/game/objects/structures/railing.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/reagents/holder.dm
Labels: Upstream PR Merged, bugfix

#428 [MIRROR] noexcutite now can be made again
  code/modules/reagents/recipes.dm
Labels: Upstream PR Merged, bugfix

#429 [MIRROR] Adds new toy figures
  code/game/machinery/computer/arcade.dm
  code/game/objects/items/toys.dm
  code/game/objects/random/purerandom.dm
  code/game/objects/random/toys.dm
  code/modules/client/preference_setup/loadout/lists/misc.dm
  icons/obj/toy.dmi
  maps/submaps/dungeon_rooms/rooms/4.dmm
  maps/submaps/dungeon_rooms/rooms/5.dmm
Labels: Feature, Map Changes, Sprites, Upstream PR Merged

#430 [MIRROR] Lowers the amount of time spawning in paralyzes you for.
  code/modules/client/preferences_spawnpoints.dm
Labels: Balance/Rebalance, Quality of Life, Upstream PR Merged

#432 [MIRROR] Nanorepair cooldown
  code/modules/mob/living/silicon/robot/drone/blitzshell.dm
Labels: Balance/Rebalance, Upstream PR Merged

#433 [MIRROR] patches the mirc error
  code/modules/reagents/recipes.dm
Labels: Balance/Rebalance, Upstream PR Merged, bugfix

#434 [MIRROR] priest and acolyte jacket should at least protect as much as a labcoat
  code/modules/clothing/suits/jobs.dm
Labels: Balance/Rebalance, Upstream PR Merged

#435 [MIRROR] Borgs/Drones light replacer recharges faster
  code/game/objects/items/devices/lightreplacer.dm
Labels: Balance/Rebalance, Quality of Life, Upstream PR Merged

#436 [MIRROR] Lasblender damage adjustment
  code/modules/projectiles/guns/energy/lasersmg.dm
Labels: Feature, Upstream PR Merged

#437 [MIRROR] Mercenary shuttle travel time is now 3 minutes
  maps/CEVEris/shuttles-eris.dm
Labels: Balance/Rebalance, Upstream PR Merged

#439 Added new species Blurbs + Misc Eris removals.
  code/game/jobs/job/guild.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/station/station_vr.dm
  code/modules/research/designs/cell.dm
  maps/CEVEris/datums/reports.dm
  maps/CEVEris/shuttles-eris.dm
Labels: Lore Compliance

#316 [MIRROR] search players in DB
  cev_eris.dme
  code/datums/topic/admin.dm
  code/global.dm
  code/modules/admin/DB_search/search.dm
  code/modules/admin/verbs/antiraid.dm
  code/modules/client/asset_cache.dm
  code/modules/client/client procs.dm
  schema.sql
Labels: Administrative, Feature, Upstream PR Merged

#246 [MIRROR] Moebius faction items
  cev_eris.dme
  code/datums/objective/steal.dm
  code/game/objects/items/devices/biosyphon.dm
  code/game/objects/items/devices/von-krabin.dm
  code/modules/reagents/enricher.dm
  icons/inventory/belt/mob.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/faction_item.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: Feature, Map Changes, Merge Conflict, Sprites, Upstream PR Merged

#276 [MIRROR] Medical Voidsuit resprite and Fate translation fix
  code/datums/perks/fate.dm
  code/datums/perks/job.dm
  code/datums/perks/oddity.dm
  code/datums/setup_option/backgrounds/fate.dm
  code/modules/clothing/spacesuits/void/station.dm
  icons/inventory/feet/icon.dmi
  icons/inventory/head/icon.dmi
  icons/inventory/head/mob.dmi
  icons/inventory/suit/icon.dmi
  icons/inventory/suit/mob.dmi
  icons/inventory/suit/mob_fem.dmi
Labels: DO NOT MERGE, Merge Conflict, Sprites, Upstream PR Merged

#310 [MIRROR] fix lowborn and absolute grab perks
  code/_onclick/click.dm
  code/_onclick/other_mobs.dm
  code/datums/setup_option/backgrounds/fate.dm
Labels: DO NOT MERGE, Feature, Merge Conflict, Upstream PR Merged

#334 [MIRROR] Faction items update
  cev_eris.dme
  code/datums/objective/steal.dm
  code/datums/perks/job.dm
  code/game/jobs/job/captain.dm
  code/game/objects/items/complicator.dm
  code/game/objects/items/devices/last_shelter.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/devices/techno_tribalism.dm
  code/game/objects/items/oddities.dm
  code/game/objects/items/weapons/maneki_neko.dm
  code/game/objects/items/weapons/sword_of_truth.dm
  code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
  code/modules/core_implant/cruciform/machinery/cloning.dm
  code/modules/core_implant/cruciform/modules.dm
  code/modules/reagents/atomic_distillery.dm
  code/modules/reagents/reagents/dispenser.dm
  code/modules/reagents/reagents/food-Drinks.dm
  code/modules/soulcrypt/base_implant.dm
  icons/obj/oddities.dmi
  maps/CEVEris/_CEV_Eris.dmm
Labels: DO NOT MERGE, Map Changes, Merge Conflict, Sprites, Upstream PR Merged

#381 [MIRROR] Item fixes
  code/modules/clothing/suits/miscellaneous.dm
Labels: Sprites, Upstream PR Merged

#467 [MIRROR] Rescue Borg: Stop the bleeding.
  code/modules/mob/living/silicon/robot/robot_modules.dm
Labels: Upstream PR Merged

#471 [MIRROR] Extinguisher Cabinants can be alt clicked to open/close
  code/game/objects/structures/extinguisher.dm
Labels: Upstream PR Merged

#472 [MIRROR] You can now Alt-click on storage containers to look inside them
  code/game/objects/items/weapons/storage/storage.dm
Labels: Upstream PR Merged

#475 [MIRROR] beanbags now actually properly check bullet armor, removes a dumb comment
  code/modules/projectiles/projectile/bullettypes.dm
Labels: Upstream PR Merged

#477 [MIRROR] Grinder detach QoL
  code/modules/reagents/machinery/grinder.dm
Labels: Upstream PR Merged

#478 [MIRROR] Chem dispenser detach QoL
  code/modules/reagents/machinery/chem_dispenser.dm
Labels: Upstream PR Merged

#485 [MIRROR] Rubber bullets get blue spites
  code/modules/projectiles/projectile/bullettypes.dm
  icons/obj/projectiles.dmi
Labels: Upstream PR Merged

#487 [MIRROR] New fire extinguisher sprites, overlays and extinguisher cabinets (sprites by WatlerJe)
  code/game/objects/items/weapons/extinguisher.dm
  code/game/objects/structures/extinguisher.dm
  code/modules/mechs/equipment/utility.dm
  icons/obj/closet.dmi
Labels: Upstream PR Merged

#494 [MIRROR] Lasblender readjustment
  code/modules/projectiles/guns/energy/lasersmg.dm
Labels: Upstream PR Merged

#504 [MIRROR] fix Runtime in lungs.dm,160
  code/modules/organs/internal/lungs.dm
Labels: Upstream PR Merged

#497 [MIRROR] Maintenance shroom rework and fix
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/spreading/spreading_response.dm
  icons/obj/hydroponics_misc.dmi
  icons/obj/hydroponics_products.dmi
Labels: Upstream PR Merged

#503 [MIRROR] fix Runtime in uplink.dm,155
  code/game/objects/items/devices/uplink.dm
Labels: Upstream PR Merged

#502 [MIRROR] fix Runtime in artifact.dm,121
  code/modules/research/xenoarchaeology/artifact/artifact.dm
Labels: Upstream PR Merged

#500 [MIRROR] Fix Runtime in preferences_spawnpoints.dm,140
  code/modules/client/preferences_spawnpoints.dm
Labels: Upstream PR Merged

#501 [MIRROR] fix Runtime in sound.dm,435
  code/game/sound.dm
Labels: Upstream PR Merged

#499 [MIRROR] Fix Runtime in item_attack.dm,77
  code/_onclick/item_attack.dm
Labels: Upstream PR Merged

#496 [MIRROR] Snacks remade (also punpun and bones return) and tweaks to moebius
  maps/CEVEris/_CEV_Eris.dmm
Labels: Upstream PR Merged

#495 [MIRROR] modification for tools upgrade force formula
  code/game/objects/items/weapons/tools/_tools.dm
  code/game/objects/items/weapons/tools/mods/_upgrades.dm
Labels: Upstream PR Merged

#489 [MIRROR] door.dm,428
  code/game/machinery/doors/door.dm
Labels: Upstream PR Merged

#486 [MIRROR] Radstorm fix: Expansion of protected areas
  code/game/gamemodes/events/weather/rad_storm.dm
Labels: Upstream PR Merged

#484 [MIRROR] Farmbot fixes
  code/modules/mob/living/bot/farmbot.dm
  icons/obj/aibots.dmi
Labels: Upstream PR Merged

#482 [MIRROR] Breakout time in seconds
  code/modules/mob/living/carbon/resist.dm
Labels: Upstream PR Merged

#387 [MIRROR] Faction items fix
  code/game/objects/items/devices/last_shelter.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/devices/techno_tribalism.dm
  code/game/objects/items/weapons/maneki_neko.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, Merge Conflict, PR dependencies, Upstream PR Merged

#466 [MIRROR] Add new bluespace storage items
  code/datums/helper_datums/teleport.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/storage/pouches.dm
  code/modules/power/singularity/act.dm
  code/modules/research/designs.dm
  code/modules/research/nodes/bluespace.dm
  icons/inventory/belt/icon.dmi
  icons/inventory/belt/mob.dmi
  icons/inventory/pockets/icon.dmi
  icons/obj/janitor.dmi
  icons/obj/storage/backpack.dmi
Labels: Upstream PR Merged

#511 [MIRROR] Fix icon update for trashbag of holding
  code/game/objects/items/weapons/storage/bags.dm
Labels: Upstream PR Merged

#512 [MIRROR] tunnel snake variants now are different
  code/modules/clothing/suits/miscellaneous.dm
Labels: Upstream PR Merged

#514 [MIRROR] Quick fix for QC logging
  code/__HELPERS/logging.dm
Labels: Upstream PR Merged

#515 [MIRROR] Quick addition for logging of GC
  code/world.dm
Labels: Upstream PR Merged
