Repository Eclipse-Station/NEV-Northern-Light, pull requests merged in 2021-08, with the labels that each got.

#1526 Chloramine port
  cev_eris.dme
  code/ATMOSPHERICS/components/omni_devices/_omni_extras.dm
  code/ATMOSPHERICS/components/omni_devices/filter.dm
  code/ATMOSPHERICS/components/omni_devices/omni_base.dm
  code/ATMOSPHERICS/components/trinary_devices/filter.dm
  code/ATMOSPHERICS/components/unary/vent_scrubber.dm
  code/defines/gases_eclipse.dm
  code/game/machinery/alarm.dm
  code/game/machinery/atmoalter/canister_eclipse.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/reagents/reagents/medicine_eclipse.dm
  code/modules/reagents/reagents/other_eclipse.dm
  code/modules/reagents/recipes_eclipse.dm
Labels: Feature, Eclipse Code Port

#1524 Softening the Autolathe Nerf
  code/game/machinery/autolathe/autolathe.dm
  code/modules/scrap/oldificator.dm
Labels: Balance/Rebalance

#1530 Neck fluff
  cev_eris.dme
  zzz_modular_eclipse/code/modules/sprite_accessories/_accessory_facial.dm
  zzz_modular_eclipse/icons/mob/hair_facial.dmi
Labels: Feature

#1531 Balancing tweaks to Benzin roaches
  code/modules/mob/living/carbon/superior_animal/roach/types/nitro.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/bullettypes.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/fragment.dm
  code/modules/projectiles/projectile/plasma.dm
  code/modules/projectiles/projectile/projectilegrenades.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/reagents/reagent_dispenser.dm
Labels: Balance/Rebalance, bugfix
