Repository Eclipse-Station/NEV-Northern-Light, pull requests merged in 2021-04, with the labels that each got.

#1466 Edit colorable underwear to use the appropriate blend type.
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Sprites, bugfix

#1467 Modular Console Fix
  code/modules/modular_computers/computers/modular_computer/interaction.dm
  code/modules/modular_computers/computers/modular_computer/variables.dm
  code/modules/modular_computers/computers/subtypes/dev_console.dm
Labels: bugfix

#1450 Mil mag fix
  code/modules/clothing/shoes/magboots.dm
Labels: Quality of Life

#1468 Fixes the code that nerfed the ever-living hell out of maintenance mushrooms, tweaked rate of spread
  code/modules/hydroponics/spreading/spreading_growth.dm
Labels: Balance/Rebalance, bugfix

#1470 Fire/air alarm audibles no longer play if unable
  code/game/machinery/alarm.dm
Labels: bugfix

#1473 Updates nIRC to LIRC
  code/modules/modular_computers/file_system/programs/medical/chem_catalog.dm
Labels: Lore Compliance

#1474 Autolathe Patch
  code/game/machinery/autolathe/autolathe.dm
Labels: bugfix

#1475 Makes inflatables not stop the hivemind wires
  code/modules/hivemind/wires.dm
Labels: bugfix

#1476 Lockers in ZeroG Fix
  code/modules/mob/mob_movement.dm
Labels: Quality of Life
