Repository Eclipse-Station/NEV-Northern-Light, pull requests merged in 2021-06, with the labels that each got.

#1480 Increases air alarm visibility in low-light conditions
  code/game/machinery/alarm.dm
  zzz_modular_eclipse/air_alarm_overlays/overlays.dmi
Labels: Eclipse edit, Quality of Life, Sprites

#1482 Fixes and balancing changes to roaches, with regards to hats
  code/modules/mob/living/carbon/superior_animal/roach/roach.dm
Labels: Balance/Rebalance, bugfix

#1481 Makes phoron glass fireproof
  code/game/objects/structures/window.dm
Labels: Balance/Rebalance, Quality of Life

#1483 Adds a GPS tracker to all drones.
  code/modules/mob/living/silicon/robot/drone/_drone.dm
  code/modules/mob/living/silicon/robot/drone/blitzshell.dm
Labels: Balance/Rebalance

#1486 Lowpop Hivemind balancing pass
  code/game/machinery/alarm.dm
  code/modules/hivemind/machines.dm
  code/modules/hivemind/mobs.dm
Labels: Balance/Rebalance, Eclipse edit, Priority: High, Quality of Life

#510 [WIP] NT dispatcher by EJC
  cev_eris.dme
  code/__DEFINES/subsystems.dm
  code/__HELPERS/logging.dm
  code/__HELPERS/text.dm
  code/controllers/configuration_eclipse.dm
  code/controllers/subsystems/dispatcher.dm
  code/controllers/subsystems/dispatcher_debug.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/requests_console.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/admin/verbs/randomverbs_eclipse.dm
  code/modules/research/message_server.dm
  code/modules/webhook/webhook.dm
  config/example/config_eclipse.txt
  maps/CEVEris/_CEV_Eris.dmm
Labels: Administrative, Config Changes, Feature, Map Changes, Work in Progress

#1488 Fixes dispatcher not caring about latejoin players
  code/controllers/subsystems/dispatcher.dm
  code/controllers/subsystems/dispatcher_debug.dm
  code/modules/client/preferences_spawnpoints.dm
Labels: bugfix

#1489 Lights can now overload, adds new fire alarm malfunction event
  cev_eris.dme
  code/game/gamemodes/events/fire_alarm.dm
  code/modules/power/apc.dm
  code/modules/power/lighting.dm
  sound/effects/transformer_overload.ogg
Labels: Eclipse edit, Feature

#1494 A few bugfixes
  code/controllers/configuration_eclipse.dm
  code/controllers/subsystems/dispatcher.dm
  code/controllers/subsystems/ticker.dm
  code/controllers/subsystems/vote.dm
  code/game/machinery/alarm.dm
  code/game/machinery/nuclear_bomb.dm
  code/modules/power/lighting.dm
  code/modules/trade/datums/trade_stations_presets/zarya.dm
  config/example/config_eclipse.txt
  sound/misc/announce_dig.ogg
Labels: Config Changes, Quality of Life, Spelling and Grammer, Sprites, bugfix

#1496 Some map fixes
  CONTRIBUTING.md
  cev_eris.dme
  code/game/objects/items/weapons/cards_ids.dm
  code/modules/power/lighting.dm
  icons/inventory/uniform/icon.dmi
  icons/inventory/uniform/mob.dmi
  icons/inventory/uniform/mob_fem.dmi
  icons/mecha/mecha64x64.dmi
  icons/mob/human_races/cyberlimbs/bishop.dmi
  icons/mob/human_races/cyberlimbs/hesphaistos.dmi
  icons/mob/human_races/cyberlimbs/xion.dmi
  icons/mob/human_races/cyberlimbs/zenghu.dmi
  icons/obj/guns/energy/martyr.dmi
  icons/obj/guns/energy/stunrevolver_moebius.dmi
  icons/obj/guns/projectile/ak.dmi
  icons/obj/guns/projectile/c20m.dmi
  icons/obj/guns/projectile/kovacs.dmi
  icons/obj/structures/junk_tractor_beam.dmi
  icons/readme.md
  maps/CEVEris/_CEV_Eris.dmm
  zzz_modular_eclipse/radio_sprites/radio_lockers.dm
Labels: Feature, Map Changes, Sprites, bugfix

#1506 Upstream fixes
  cev_eris.dme
  code/__DEFINES/plumbing.dm
  code/controllers/subsystems/machines.dm
  code/datums/components/plumbing/_plumbing.dm
  code/datums/craft/recipes/machinery.dm
  code/datums/ductnet.dm
  code/game/objects/items/weapons/design_disks/technomancers.dm
  code/modules/biomatter_manipulation/biogenerator.dm
  code/modules/biomatter_manipulation/solidifier.dm
  code/modules/core_implant/cruciform/machinery/cloning.dm
  code/modules/hivemind/core.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/plumbing/ducts.dm
  code/modules/plumbing/plumbers/_plumb_machinery.dm
  code/modules/plumbing/plumbers/bottler.dm
  code/modules/plumbing/plumbers/destroyer.dm
  code/modules/plumbing/plunger.dm
  code/modules/reagents/reagent_dispenser.dm
  code/modules/research/nodes/engineering.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
  html/changelogs/AutoChangeLog-pr-6359.yml
  maps/CEVEris/_CEV_Eris.dmm
Labels: Quality of Life, Upstream PR Merged
