Repository Eclipse-Station/NEV-Northern-Light, pull requests merged in 2021-09, with the labels that each got.

#1541 Update vending_eclipse.dm
  code/game/machinery/vending_eclipse.dm
Labels: bugfix

#1542 Remove stashed commit
  maps/CEVEris/_CEV_Eris.dmm
Labels: Map Changes, Priority: Critical, Priority: High, bugfix, Manual CI check: PASS

#1539 Vanity update Part 1
  cev_eris.dme
  code/game/machinery/jukebox.dm
  code/game/objects/structures/barsign.dm
  code/modules/client/preference_setup/loadout/lists/custom.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/media/media_tracks.dm
  zzz_modular_eclipse/code/modules/objects/items/tapes.dm
  zzz_modular_eclipse/icons/custom_items/casettes.dmi
  zzz_modular_eclipse/icons/obj/barsign-blue.dmi
  zzz_modular_eclipse/icons/obj/barsign-eclipse.dmi
Labels: Feature

#1547 Fixes welding fuel behaviour with regards to Z-levels
  code/game/objects/effects/decals/Cleanable/fuel.dm
  code/modules/mob/living/carbon/superior_animal/roach/types/nitro.dm
Labels: bugfix

#1546 Vine spawn restrictions
  code/game/objects/structures/burrows.dm
  code/modules/hydroponics/spreading/spacevines.dm
Labels: Balance/Rebalance, Quality of Life, Maintainer testing: PASS
