Repository Eclipse-Station/NEV-Northern-Light, pull requests merged in 2021-11, with the labels that each got.

#1566 Spider Nest
  cev_eris.dme
  code/game/gamemodes/events/hidden_events/spider_nest.dm
Labels: Balance/Rebalance, Feature

#1572 Stonks and Shields
  code/controllers/subsystems/economy.dm
  code/game/jobs/department.dm
  code/game/jobs/job/security.dm
  code/game/machinery/cryopod.dm
  code/modules/modular_computers/file_system/reports/crew_record.dm
  code/modules/shield_generators/modes.dm
  maps/CEVEris/_CEV_Eris.dmm
Labels: Balance/Rebalance, Map Changes, bugfix

#1576 Switches the Borg text to properly display locking and unlocking in c…
  code/modules/mob/living/silicon/robot/robot.dm
Labels: bugfix

#1571 Comments out periodic player-tracking updates.
  code/controllers/subsystems/dispatcher.dm
Labels: Administrative

#1569 Event changes
  cev_eris.dme
  code/game/gamemodes/events/alarm_malfunction.dm
  code/game/gamemodes/events/blob.dm
  code/game/gamemodes/events/comms_brownout.dm
  code/game/gamemodes/events/fire_alarm.dm
  code/game/gamemodes/events/gas_leak.dm
  code/game/gamemodes/events/hivemind_invasion.dm
  code/game/gamemodes/storyteller.dm
  code/game/gamemodes/storytellers/chronicler.dm
  code/game/gamemodes/storytellers/healer.dm
  code/game/machinery/alarm.dm
  code/modules/hydroponics/seed.dm
  code/modules/hydroponics/spreading/spacevines.dm
  code/modules/hydroponics/spreading/spreading.dm
  code/modules/hydroponics/spreading/spreading_growth.dm
Labels: Balance/Rebalance, Feature

#1579 Update miscellaneous.dm
  code/modules/clothing/masks/miscellaneous.dm
Labels: Balance/Rebalance

#1586 Valanthe bugfixing
  code/datums/outfits/jobs/guild.dm
  code/datums/outfits/jobs/medical.dm
  code/datums/outfits/jobs/science.dm
  code/datums/outfits/jobs/security.dm
  code/game/objects/items/devices/lighting/glowstick.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/weapons/handcuffs.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/new_player/new_player.dm
Labels: Priority: High, bugfix

#1588 Custom Items - Ready for review
  code/modules/client/preference_setup/loadout/lists/custom.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/suits/jobs.dm
  config/custom_items.txt
  zzz_modular_eclipse/code/modules/custom_items/itemlist.dm
  zzz_modular_eclipse/icons/custom_items/mob.dmi
  zzz_modular_eclipse/icons/custom_items/shoes.dmi
  zzz_modular_eclipse/icons/custom_items/suit.dmi
  zzz_modular_eclipse/icons/custom_items/under.dmi
Labels: Feature

#1594 Re-adds hub flair
  code/game/world.dm
Labels: Priority: High, Administrative
