Repository Eclipse-Station/NEV-Northern-Light, pull requests merged in 2022-05, with the labels that each got.

#1666 Shield generator overheat fix
  code/modules/shield_generators/shield_generator.dm
Labels: Priority: High, bugfix, Quality of Life

#1660 Magisterium2022 patch borer fix
  code/modules/mob/living/simple_animal/borer/borer.dm
Labels: bugfix

#1668 Update chem_dispenser.dm
  code/modules/reagents/machinery/chem_dispenser.dm
Labels: Priority: High, bugfix
