Repository Eclipse-Station/NEV-Northern-Light, pull requests merged in 2022-09, with the labels that each got.

#1683 Adds Vermin
  cev_eris.dme
  code/game/gamemodes/events/vermin.dm
  code/modules/mob/living/simple_animal/vermin.dm
  sound/effects/vermin/vermin1.ogg
  sound/effects/vermin/vermin2.ogg
  sound/effects/vermin/vermin3.ogg
  sound/effects/vermin/vermin4.ogg
Labels: Feature

#1686 Project jackboot Phase 1 - Map Updates
  cev_eris.dme
  maps/CEVEris/_CEV_Erida.dmm
  maps/CEVEris/centcomm.dmm
  maps/CEVEris/shuttles-eris.dm
  zzz_modular_eclipse/code/maps/NEVNothern_Light/shuttles-eclipse.dm
Labels: Map Changes, Map: Erida, Map: Central Command

#1691 Admins (and players, if no admins are on) are now warned if the mobs subsystem has too much to handle.
  code/controllers/subsystems/processing/mobs.dm
Labels: Priority: Critical, Priority: High, Administrative, Maintainer testing: PASS
