Repository Eclipse-Station/NEV-Northern-Light, pull requests merged in 2025-07, with the labels that each got.

#1822 Fix debug guns in armoury and missing floor tile in church
  maps/CEVEris/_CEV_Erida.dmm
Labels: Map Changes, bugfix, Map: Eris

#1827 Updates _compiler_options.dm to include a warning when you try to compile on 515.
  code/_compile_options.dm
Labels: Eclipse edit, Tools, Administrative

#1793 Whitelist Patch
  code/game/jobs/whitelist.dm
Labels: CI failure, bugfix

#1828 Changelog compiler tweaks
  tools/changelog/generate_cl.py
Labels: GitHub/CI, Tools

#1831 Updates workflows for futureproofing
  .github/workflows/compile_changelogs.yml
  .github/workflows/conflicts.yml
  .github/workflows/generate_documentation.yml
  .github/workflows/show_screenshot_test_results.yml
Labels: GitHub/CI

#1829 map fixes
  maps/CEVEris/_CEV_Erida.dmm
Labels: Map Changes, Map: Erida

#1834 Linterchan Whispering 2.0
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_control.dm
  code/game/machinery/doors/door.dm
  code/modules/pulsar_engine/pulsar_consoles.dm
  icons/inventory/pockets/icon.dmi
  icons/obj/doors/door_assembly.dmi
  icons/obj/doors/windoor.dmi
  icons/obj/guns/launcher/pneumatic.dmi
  icons/obj/items.dmi
  icons/obj/sheath.dmi
  icons/obj/turrets.dmi
  icons/obj/weapons.dmi
Labels: GitHub/CI, bugfix, Ready for review

#1833 Revert TGUI changes
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui-say.bundle.js
  tgui/public/tgui.bundle.js
Labels: Priority: High, Spitzer's Bane, javascript

#1837 Fixes Techno Enforcer saving
  code/modules/multiz/map_data.dm
Labels: bugfix

#1839 Iso's First Officer outfit added to the game.
  cev_eris.dme
  code/modules/client/preference_setup/loadout/lists/footwear.dm
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/client/preference_setup/loadout/lists/uniforms.dm
  zzz_modular_eclipse/code/modules/clothing/feet/bricheese.dm
  zzz_modular_eclipse/code/modules/clothing/suit/bricheese.dm
  zzz_modular_eclipse/code/modules/clothing/uniform/bricheese.dm
  zzz_modular_eclipse/icons/bri_clothing/feet/item.dmi
  zzz_modular_eclipse/icons/bri_clothing/feet/mob.dmi
  zzz_modular_eclipse/icons/bri_clothing/suit/item.dmi
  zzz_modular_eclipse/icons/bri_clothing/suit/mob.dmi
  zzz_modular_eclipse/icons/bri_clothing/uniform/item.dmi
  zzz_modular_eclipse/icons/bri_clothing/uniform/mob.dmi
Labels: Feature, Sprites
