Repository Eclipse-Station/NEV-Northern-Light, pull requests merged in 2025-06, with the labels that each got.

#1800 Fixes for some tool operations
  code/game/machinery/antigrav.dm
  code/game/machinery/recharger.dm
  code/game/objects/items/weapons/nt_melee.dm
  code/game/objects/items/weapons/sword_of_truth.dm
  code/game/objects/structures/artwork_statue.dm
Labels: CI failure, Eclipse edit, bugfix

#1802 Fixes oddies not being detected in clothing
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/rig/modules/modules.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/mob/living/living.dm
Labels: CI failure, Eclipse edit, bugfix

#1805 bioreactor buildable
  code/modules/core_implant/cruciform/rituals/construction.dm
Labels: CI failure, Eclipse edit, bugfix

#1808 Fixes autolathen mater douping
  code/game/machinery/autolathe/autolathe.dm
Labels: CI failure, Eclipse edit, bugfix

#1799 fixes lipstick
  icons/mob/human_face.dmi
Labels: CI failure, Sprites, PR dependencies

#1815 Fixes shoe overlay
  icons/inventory/feet/icon.dmi
Labels: CI failure, Sprites

#1816 untabbed adv_med
  code/game/machinery/adv_med.dm
Labels: CI failure, bugfix

#1810 Adds configuration options for the shield generator
  code/controllers/configuration_eclipse.dm
  code/modules/shield_generators/shield_generator.dm
  config/example/config_eclipse.txt
Labels: CI failure, Priority: Critical, Priority: High, Administrative, Config Changes, Maintainer testing: PASS, Testmerged

#1817 Shield generator room update, basic semiotic signage pass
  maps/CEVEris/_CEV_Erida.dmm
Labels: Balance/Rebalance, CI failure, Map Changes, Priority: High, bugfix, Maintainer testing: PASS, Map: Eris
